site_name: MNE-BIDS-Pipeline
repo_url: https://github.com/mne-tools/mne-bids-pipeline
edit_uri: edit/main/docs/source/
site_description: The MNE-BIDS-Pipeline is a collection of scripts for automated processing of MEG and EEG data.
site_author: MNE-BIDS-Pipeline authors
docs_dir: ./source
site_dir: ./site
use_directory_urls: false  # For easier navigation on CircleCI
theme:
    name: material
    logo: assets/mne.svg
    favicon: assets/favicon.ico
    features:
        - navigation.tabs
        - navigation.instant  # Load pages via XMLHttpRequest (XHR)
        - navigation.tracking
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/mne-tools/mne-bids-pipeline
          name: GitHub repository
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/mne_news
          name: MNE news on Twitter

copyright: Copyright &copy; MNE-BIDS-Pipeline authors

extra_css:
    - css/extra.css
nav:
    - Home: index.md
    - Getting started:
        - Installation: getting_started/install.md
        - Basic usage: getting_started/basic_usage.md
        - Preparations for source-level analyses: getting_started/freesurfer.md
    - Features:
        - What the pipeline can do: features/features.md
        - List of processing steps: features/steps.md
    - Configuration Options:
        - General settings: settings/general.md
        - Preprocessing:
            - Break detection: settings/preprocessing/breaks.md
            - Bad channel detection: settings/preprocessing/autobads.md
            - Maxwell filter: settings/preprocessing/maxfilter.md
            - Filtering & resampling:
                - Filtering: settings/preprocessing/filter.md
                - Resampling: settings/preprocessing/resample.md
            - Epoching: settings/preprocessing/epochs.md
            - Artifact removal:
                - Stimulation artifact: settings/preprocessing/stim_artifact.md
                - SSP & ICA: settings/preprocessing/ssp_ica.md
                - Amplitude-based: settings/preprocessing/artifacts.md
        - Sensor-level analysis:
            - Statistics: settings/sensor/statistics.md
            - Time-frequency analysis: settings/sensor/time_freq.md
            - Group-level analysis: settings/sensor/group_level.md
        - Source-level analysis:
            - General settings: settings/source/general.md
            - BEM surface: settings/source/bem.md
            - Source space & forward solution: settings/source/forward.md
            - Inverse solution: settings/source/inverse.md
        - Report:
            - HTML Report: settings/report/report.md
    - Examples:
        - Examples Gallery: examples/examples.md
        - examples/ds003392.md
        - examples/ds004229.md
        - examples/ds000246.md
        - examples/ds000247.md
        - examples/ds000248.md
        - examples/ds000248_ica.md
        # - examples/ds000248_T1_BEM.md
        # - examples/ds000248_FLASH_BEM.md
        - examples/ds000248_no_mri.md
        - examples/ds003104.md
        - examples/eeg_matchingpennies.md
        - examples/ds001810.md
        - examples/ds000117.md
        - examples/ds003775.md
        - examples/ds004107.md
        - examples/ds001971.md
        - examples/ERP_CORE.md
    - What's new: changes.md

plugins:
    - search
    - macros
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                rendering:
                    show_source: true
                    show_if_no_docstring: false
                    show_root_heading: true
                    show_root_full_path: false
                    separate_signature: true
                    show_bases: false
                selection:
                    docstring_style: numpy
        watch:
            - .
            - ./config.py
markdown_extensions:
    - admonition
    - abbr
    - attr_list  # Allows to turn any element into a button
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences
    - toc:
        permalink: true  # Add paragraph symbol to link to current headline
