site_name: MNE Study Template
repo_url: https://github.com/mne-tools/mne-study-template
site_description: The MNE Study Template is a collection of scripts for automated processing of MEG and EEG data.
site_author: MNE Study Template authors
docs_dir: ./source
site_dir: ./site
use_directory_urls: false  # For easier navigation on CircleCI
theme:
    name: material
    logo: assets/mne.svg
    favicon: assets/favicon.ico
    features:
        - navigation.tabs
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/mne-stools/mne-study-template
          name: GitHub repository
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/mne_news
          name: MNE news on Twitter
    
copyright: Copyright &copy; MNE Study Template authors
 
extra_css:
    - css/extra.css
nav:
    - Introduction: index.md
    - Installation: install.md
    - Getting Started: getting_started.md
    - Processing Steps: 
        - List of steps: steps/steps.md
    - Configuration Options:
        - Basic settings: settings/basic.md
        - Continuous data:
            - Bad channel detection: settings/continuous_data/autobads.md
            - Maxwell filter: settings/continuous_data/maxfilter.md
            - Stimulation artifact: settings/continuous_data/stim_artifact.md
            - Frequency filtering & resampling:
                - Filtering: settings/continuous_data/filter.md
                - Resampling: settings/continuous_data/resample.md
        - Epoched data:
            - Epoching: settings/epoched_data/epochs.md
            - Amplitude-based artifact removal: settings/epoched_data/artifacts.md
            - SSP & ICA: settings/epoched_data/ssp_ica.md
            - Statistics: settings/epoched_data/statistics.md
            - Time-frequency analysis: settings/epoched_data/time_freq.md
        - Source estimation: settings/epoched_data/inverse.md

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                setup_commands:
                    - import os
                    - os.environ["MNE_BIDS_STUDY_CONFIG"] = "./source/doc-config.py"
                    - import sys
                    - sys.path.insert(0, "..")
                rendering:
                    show_source: true
                    show_if_no_docstring: false
                    show_root_heading: true
                    show_root_full_path: false
        watch:
            - .
            - ./config.py
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed
    - toc:
        permalink: true  # Add paragraph symbol to link to current headline
