name: uv lock

on:  # yamllint disable-line rule:truthy
  # Scheduled actions only run on the main repo branch, which is exactly what we want
  schedule:
    - cron: '0 0 * * 0'  # weekly on Sunday at 00:00
  workflow_dispatch:

jobs:
  upgrade:
    permissions:
      contents: write
      pull-requests: write
    name: upgrade
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.MNE_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.MNE_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
      - uses: astral-sh/setup-uv@v7
      - run: uv lock --upgrade
      - run: |
          git diff && git status --porcelain
          if [[ $(git status --porcelain) ]]; then
            echo "dirty=true" >> $GITHUB_OUTPUT
          fi
        id: status
      - name: Create PR
        run: |
          set -xeo pipefail
          git config --global user.email "50266005+mne-bot@users.noreply.github.com"
          git config --global user.name "mne[bot]"
          BRANCH=uv/$GITHUB_RUN_ID
          git checkout -b $BRANCH
          git commit -am "mne[bot]: Update uv"
          git push origin $BRANCH
          PR_NUM=$(gh pr create --base main --head $BRANCH --title "MAINT: Update uv" --body "Created by uv [GitHub action](https://github.com/mne-tools/mne-bids-pipeline/actions/runs/${{ github.run_id }})")
          echo "Opened https://github.com/mne-tools/mne-bids-pipeline/pull/${PR_NUM}" >> $GITHUB_STEP_SUMMARY
        if: steps.status.outputs.dirty == 'true'
